"""phase1-8-full-coverage

Revision ID: 14a7b9398bb7
Revises: 
Create Date: 2026-04-17 18:51:18.454542

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '14a7b9398bb7'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_provider_configs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('provider', sa.String(), nullable=False),
    sa.Column('model_key', sa.String(), nullable=False),
    sa.Column('display_name', sa.String(), nullable=False),
    sa.Column('task_types', sa.String(), nullable=False),
    sa.Column('capabilities_json', sa.String(), nullable=True),
    sa.Column('enabled', sa.Integer(), nullable=False),
    sa.Column('api_key', sa.String(), nullable=True),
    sa.Column('base_url', sa.String(), nullable=True),
    sa.Column('config_json', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('model_key')
    )
    op.create_table('subscription_plans',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('monthly_price_usd', sa.Float(), nullable=False),
    sa.Column('quotas_json', sa.String(), nullable=False),
    sa.Column('features_json', sa.String(), nullable=False),
    sa.Column('is_active', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('user_type', sa.String(), nullable=False),
    sa.Column('oauth_provider', sa.String(), nullable=True),
    sa.Column('oauth_id', sa.String(), nullable=True),
    sa.Column('avatar_url', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('workspaces',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('plan_tier', sa.String(), nullable=False),
    sa.Column('lifecycle_status', sa.Enum('trial', 'active', 'grace_period', 'suspended', 'cancelled', name='workspacelifecycle', native_enum=False), nullable=False),
    sa.Column('storage_quota_mb', sa.Integer(), nullable=False),
    sa.Column('raw_retention_days', sa.Integer(), nullable=False),
    sa.Column('autonomy_mode', sa.Enum('supervised', 'review_then_publish', 'auto_publish', name='autonomymode', native_enum=False), nullable=True),
    sa.Column('autonomy_confidence_threshold', sa.Float(), nullable=True),
    sa.Column('autopublish_platforms', sa.String(), nullable=True),
    sa.Column('quiet_hours', sa.String(), nullable=True),
    sa.Column('notification_preferences', sa.String(), nullable=True),
    sa.Column('ai_policy', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('admin_action_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('admin_user_id', sa.String(length=36), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('target_type', sa.String(), nullable=False),
    sa.Column('target_id', sa.String(), nullable=True),
    sa.Column('reason', sa.String(), nullable=True),
    sa.Column('metadata_json', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['admin_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ai_provider_credentials',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('provider', sa.Enum('anthropic', 'openai', 'vertex', 'gemini', 'deepgram', 'dashscope', name='aiprovider', native_enum=False), nullable=False),
    sa.Column('credential_source', sa.Enum('platform', 'byok', name='credentialsource', native_enum=False), nullable=False),
    sa.Column('label', sa.String(), nullable=True),
    sa.Column('api_key', sa.String(), nullable=False),
    sa.Column('allowed_models', sa.String(), nullable=True),
    sa.Column('is_active', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('app_settings',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('value', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workspace_id', 'key', name='uq_app_settings_workspace_key')
    )
    op.create_table('assets',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('file_path', sa.String(), nullable=False),
    sa.Column('asset_type', sa.Enum('music', 'sfx', name='assettype', native_enum=False), nullable=False),
    sa.Column('duration', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('audit_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('actor', sa.String(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('target_type', sa.String(), nullable=False),
    sa.Column('target_id', sa.String(), nullable=True),
    sa.Column('reason', sa.String(), nullable=True),
    sa.Column('metadata_json', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('auth_sessions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    op.create_table('background_jobs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('workspace_id', sa.String(length=36), nullable=True),
    sa.Column('job_type', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'running', 'succeeded', 'failed', 'dead_letter', name='jobstatus', native_enum=False), nullable=False),
    sa.Column('correlation_id', sa.String(), nullable=False),
    sa.Column('idempotency_key', sa.String(), nullable=True),
    sa.Column('payload_json', sa.String(), nullable=False),
    sa.Column('result_json', sa.String(), nullable=True),
    sa.Column('next_attempt_at', sa.DateTime(), nullable=True),
    sa.Column('lease_owner', sa.String(), nullable=True),
    sa.Column('lease_expires_at', sa.DateTime(), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key')
    )
    op.create_table('compliance_exports',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('requested_by_user_id', sa.String(length=36), nullable=True),
    sa.Column('export_type', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('requested', 'processing', 'completed', 'failed', name='complianceexportstatus', native_enum=False), nullable=False),
    sa.Column('storage_uri', sa.String(), nullable=True),
    sa.Column('filters_json', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['requested_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('device_tokens',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('platform', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'token', name='uq_device_token_user')
    )
    op.create_table('invitations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('invited_by', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['invited_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    op.create_table('memberships',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notifications',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('body', sa.String(), nullable=False),
    sa.Column('read_at', sa.DateTime(), nullable=True),
    sa.Column('metadata_json', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('onboarding_states',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('checklist_json', sa.String(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workspace_id')
    )
    op.create_table('platform_auth',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('platform', sa.Enum('youtube', 'tiktok', 'instagram_reels', 'linkedin', 'x', name='platformtype', native_enum=False), nullable=False),
    sa.Column('access_token_enc', sa.LargeBinary(), nullable=True),
    sa.Column('refresh_token_enc', sa.LargeBinary(), nullable=True),
    sa.Column('token_expires_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_platform_auth_status_expires', 'platform_auth', ['status', 'token_expires_at'], unique=False)
    op.create_table('platform_auth_states',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('platform', sa.Enum('youtube', 'tiktok', 'instagram_reels', 'linkedin', 'x', name='platformtype', native_enum=False), nullable=False),
    sa.Column('state', sa.String(), nullable=False),
    sa.Column('code_verifier', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('state')
    )
    op.create_table('platform_connections',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('platform', sa.Enum('youtube', 'tiktok', 'instagram_reels', 'linkedin', 'x', name='platformtype', native_enum=False), nullable=False),
    sa.Column('account_name', sa.String(), nullable=True),
    sa.Column('account_id', sa.String(), nullable=True),
    sa.Column('access_token', sa.String(), nullable=True),
    sa.Column('refresh_token', sa.String(), nullable=True),
    sa.Column('token_expiry', sa.DateTime(), nullable=True),
    sa.Column('metadata_json', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('projects',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('watch_directory', sa.String(), nullable=True),
    sa.Column('intake_mode', sa.Enum('upload', 'watch', 'api', name='intakemode', native_enum=False), nullable=False),
    sa.Column('source_type', sa.String(), nullable=True),
    sa.Column('storage_prefix', sa.String(), nullable=True),
    sa.Column('autonomy_mode', sa.Enum('supervised', 'review_then_publish', 'auto_publish', name='autonomymode', native_enum=False), nullable=True),
    sa.Column('autonomy_policy', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('selected_title', sa.String(), nullable=True),
    sa.Column('video_description', sa.String(), nullable=True),
    sa.Column('video_tags', sa.String(), nullable=True),
    sa.Column('video_category', sa.String(), nullable=True),
    sa.Column('video_visibility', sa.String(), nullable=True),
    sa.Column('selected_thumbnail_idx', sa.Integer(), nullable=True),
    sa.Column('desc_system_prompt', sa.String(), nullable=True),
    sa.Column('thumbnail_urls', sa.String(), nullable=True),
    sa.Column('locked_thumbnail_indices', sa.String(), nullable=True),
    sa.Column('thumbnail_text', sa.String(), nullable=True),
    sa.Column('render_path', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('quota_policies',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('storage_quota_mb', sa.Integer(), nullable=False),
    sa.Column('ai_spend_cap_usd', sa.Float(), nullable=False),
    sa.Column('render_minutes_quota', sa.Integer(), nullable=False),
    sa.Column('connected_platforms_quota', sa.Integer(), nullable=False),
    sa.Column('team_seats_quota', sa.Integer(), nullable=False),
    sa.Column('retained_footage_days', sa.Integer(), nullable=False),
    sa.Column('automation_max_mode', sa.String(), nullable=False),
    sa.Column('hard_enforcement', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workspace_id')
    )
    op.create_table('workspace_subscriptions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('plan_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.Enum('trial', 'active', 'grace_period', 'suspended', 'cancelled', name='subscriptionstatus', native_enum=False), nullable=False),
    sa.Column('stripe_customer_id', sa.String(), nullable=True),
    sa.Column('stripe_subscription_id', sa.String(), nullable=True),
    sa.Column('stripe_price_id', sa.String(), nullable=True),
    sa.Column('billing_email', sa.String(), nullable=True),
    sa.Column('current_period_start', sa.DateTime(), nullable=True),
    sa.Column('current_period_end', sa.DateTime(), nullable=True),
    sa.Column('cancel_at', sa.DateTime(), nullable=True),
    sa.Column('metadata_json', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['plan_id'], ['subscription_plans.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workspace_id')
    )
    op.create_table('caption_items',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('text', sa.String(), nullable=False),
    sa.Column('start_time', sa.Float(), nullable=False),
    sa.Column('end_time', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('clips',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('source_path', sa.String(), nullable=False),
    sa.Column('processed_path', sa.String(), nullable=True),
    sa.Column('clip_type', sa.Enum('talking', 'broll', 'remix', name='cliptype', native_enum=False), nullable=True),
    sa.Column('status', sa.Enum('pending', 'transcribing', 'classifying', 'processing', 'done', 'error', name='processingstatus', native_enum=False), nullable=True),
    sa.Column('review_status', sa.Enum('pending_review', 'auto_approved', 'approved', 'rejected', 'scheduled', 'publishing', 'published', 'failed', name='reviewstatus', native_enum=False), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('duration', sa.Float(), nullable=True),
    sa.Column('recorded_at', sa.DateTime(), nullable=True),
    sa.Column('transcript', sa.String(), nullable=True),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('invoices',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('subscription_id', sa.String(length=36), nullable=True),
    sa.Column('period_start', sa.DateTime(), nullable=False),
    sa.Column('period_end', sa.DateTime(), nullable=False),
    sa.Column('amount_usd', sa.Float(), nullable=False),
    sa.Column('status', sa.Enum('draft', 'open', 'paid', 'void', name='invoicestatus', native_enum=False), nullable=False),
    sa.Column('line_items_json', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['subscription_id'], ['workspace_subscriptions.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('music_items',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('asset_id', sa.String(length=36), nullable=False),
    sa.Column('start_time', sa.Float(), nullable=False),
    sa.Column('end_time', sa.Float(), nullable=False),
    sa.Column('volume', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('style_profiles',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('genre', sa.String(), nullable=True),
    sa.Column('style_doc', sa.String(), nullable=True),
    sa.Column('confidence_scores', sa.String(), nullable=True),
    sa.Column('dimension_locks', sa.String(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('mem0_user_id', sa.String(), nullable=True),
    sa.Column('brand_kit', sa.String(), nullable=True),
    sa.Column('platform_targets', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('subscribe_items',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('text', sa.String(), nullable=False),
    sa.Column('start_time', sa.Float(), nullable=False),
    sa.Column('end_time', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('timestamp_items',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('text', sa.String(), nullable=False),
    sa.Column('start_time', sa.Float(), nullable=False),
    sa.Column('end_time', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('title_items',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('text', sa.String(), nullable=False),
    sa.Column('start_time', sa.Float(), nullable=False),
    sa.Column('end_time', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tracker_items',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('start_time', sa.Float(), nullable=False),
    sa.Column('end_time', sa.Float(), nullable=False),
    sa.Column('overlay_path', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('upload_sessions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=True),
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('storage_path', sa.String(), nullable=False),
    sa.Column('total_size', sa.Integer(), nullable=True),
    sa.Column('uploaded_size', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('media_type', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usage_ledger',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=True),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(), nullable=False),
    sa.Column('amount_usd', sa.Float(), nullable=False),
    sa.Column('correlation_id', sa.String(), nullable=False),
    sa.Column('metadata_json', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ai_usage_records',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('project_id', sa.String(length=36), nullable=True),
    sa.Column('clip_id', sa.String(length=36), nullable=True),
    sa.Column('task_type', sa.String(), nullable=False),
    sa.Column('provider', sa.Enum('anthropic', 'openai', 'vertex', 'gemini', 'deepgram', 'dashscope', name='aiprovider', native_enum=False), nullable=False),
    sa.Column('model', sa.String(), nullable=False),
    sa.Column('credential_source', sa.Enum('platform', 'byok', name='credentialsource', native_enum=False), nullable=False),
    sa.Column('request_units', sa.Float(), nullable=True),
    sa.Column('response_units', sa.Float(), nullable=True),
    sa.Column('cost_estimate', sa.Float(), nullable=True),
    sa.Column('latency_ms', sa.Float(), nullable=True),
    sa.Column('status', sa.Enum('success', 'error', name='aiusagestatus', native_enum=False), nullable=False),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.Column('correlation_id', sa.String(), nullable=False),
    sa.Column('metadata_json', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['clip_id'], ['clips.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('calendar_slots',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('clip_id', sa.String(length=36), nullable=True),
    sa.Column('render_variant', sa.String(), nullable=True),
    sa.Column('platform', sa.Enum('youtube', 'tiktok', 'instagram_reels', 'linkedin', 'x', name='platformtype', native_enum=False), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('publish_url', sa.String(), nullable=True),
    sa.Column('failure_reason', sa.String(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('correlation_id', sa.String(), nullable=True),
    sa.Column('metadata_json', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['clip_id'], ['clips.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sub_clips',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('clip_id', sa.String(length=36), nullable=False),
    sa.Column('start_time', sa.Float(), nullable=False),
    sa.Column('end_time', sa.Float(), nullable=False),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('label', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['clip_id'], ['clips.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('timeline_items',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('clip_id', sa.String(length=36), nullable=True),
    sa.Column('sub_clip_id', sa.String(length=36), nullable=True),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['clip_id'], ['clips.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['sub_clip_id'], ['sub_clips.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index("ix_calendar_slots_scheduled_status", "calendar_slots", ["scheduled_at", "status"])
    op.create_index("ix_platform_auth_expires_at", "platform_auth", ["token_expires_at"])
    op.create_index("ix_ai_usage_workspace_task", "ai_usage_records", ["workspace_id", "task_type"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('timeline_items')
    op.drop_table('sub_clips')
    op.drop_table('calendar_slots')
    op.drop_table('ai_usage_records')
    op.drop_table('usage_ledger')
    op.drop_table('upload_sessions')
    op.drop_table('tracker_items')
    op.drop_table('title_items')
    op.drop_table('timestamp_items')
    op.drop_table('subscribe_items')
    op.drop_table('style_profiles')
    op.drop_table('music_items')
    op.drop_table('invoices')
    op.drop_table('clips')
    op.drop_table('caption_items')
    op.drop_table('workspace_subscriptions')
    op.drop_table('quota_policies')
    op.drop_table('projects')
    op.drop_table('platform_connections')
    op.drop_table('platform_auth_states')
    op.drop_index('ix_platform_auth_status_expires', table_name='platform_auth')
    op.drop_table('platform_auth')
    op.drop_table('onboarding_states')
    op.drop_table('notifications')
    op.drop_table('memberships')
    op.drop_table('invitations')
    op.drop_table('device_tokens')
    op.drop_table('compliance_exports')
    op.drop_table('background_jobs')
    op.drop_table('auth_sessions')
    op.drop_table('audit_logs')
    op.drop_table('assets')
    op.drop_table('app_settings')
    op.drop_table('ai_provider_credentials')
    op.drop_table('admin_action_logs')
    op.drop_table('workspaces')
    op.drop_table('users')
    op.drop_table('subscription_plans')
    op.drop_table('ai_provider_configs')
    op.drop_index("ix_calendar_slots_scheduled_status", table_name="calendar_slots")
    op.drop_index("ix_platform_auth_expires_at", table_name="platform_auth")
    op.drop_index("ix_ai_usage_workspace_task", table_name="ai_usage_records")
    # ### end Alembic commands ###
